### PR TITLE
Pr/feature/objectness fix

### PR DESCRIPTION
**Pull request by k-okada**
@mqcmd196 resolve conflict based on #1, hope this also pass GithubAction.
see https://github.com/k-okada/opencv_apps/actions/runs/2158113026

### CODE REVIEW

**Comment by mqcmd196** [comment]
@k-okada 
Thank you for your help. Another error occured
```
+ set +x
+ git -C /home/runner/work/opencv_apps/opencv_apps --no-pager diff
traivs_time:end:yrcnl0w2:start=1649806685781662080,finish=1649806867586839372,duration=181805177292

traivs_fold:end:clang_tidy.script
Function clang_tidy.script takes 3 min 1 sec
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>
Error: Process completed with exit code 129.
```

**Comment by k-okada** [comment]
https://github.com/k-okada/opencv_apps/actions/runs/2158582630

**Comment by k-okada** [comment]
https://github.com/k-okada/opencv_apps/actions/runs/2158696711

**Comment by mqcmd196** [comment]
@k-okada
LGTM, thanks a lot for your kind help!!

**Pull request merged**
